const actionTypes = {
  TOGGLE_INSTOCK: "TOGGLE_INSTOCK",
  SORT_ASCENDING: "SORT_ASCENDING",
  SORT_DESCENDING: "SORT_DESCENDING",
  CHANGE_PRICE_RANGE: "CHANGE_PRICE_RANGE",
  CHANGE_CATEGORIES: "CHANGE_CATEGORIES",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  CHANGE_RATING: "CHANGE_RATING",
  CLEAR_CATEGORIES: "CLEAR_CATEGORIES",
};

export { actionTypes };
