const actionTypes = {
  TOGGLE_INSTOCK: "TOGGLE_INSTOCK",
  SORT_ASCENDING: "SORT_ASCENDING",
  SORT_DESCENDING: "SORT_DESCENDING",
  CHANGE_PRICE_RANGE: "CHANGE_PRICE_RANGE",
  CHANGE_CATEGORIES: "CHANGE_CATEGORIES",
  SET_SEARCH: "SET_SEARCH",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  CHANGE_RATING: "CHANGE_RATING",
  CLEAR_CATEGORIES: "CLEAR_CATEGORIES",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SET_SINGLE_CATEGORY: "SET_SINGLE_CATEGORY",
  ADD_TO_ORDERS: "ADD_TO_ORDERS",
};

export { actionTypes };
